default_platform(:android)

platform :android do
  desc "Android Firebase App Distribution Lane."
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:178378327043:android:fd68b1d63e3e1ff3db7a36",
      firebase_cli_token: ENV[FIREBASE_CLI_SECRET],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "souhaibzarai18@gmail.com, szaraidev@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution Practice"
    )
  end
end
